AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Native Spring Cloud Lambda with API Gateway

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: provided.al2
    Architectures:
      - x86_64

Resources:
  PersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: person-crud
      Handler: bootstrap
      CodeUri: ./target/function.zip
      Events:
        GetPerson:
          Type: Api
          Properties:
            Path: /person/{id}
            Method: get
        CreatePerson:
          Type: Api
          Properties:
            Path: /person
            Method: post
        DeletePerson:
          Type: Api
          Properties:
            Path: /person/{id}
            Method: delete
        ListPersons:
          Type: Api
          Properties:
            Path: /person
            Method: get