name: Build and Deploy to AWS Lambda with SAM

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build:
    name: Build native image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        run: |
          mvn clean package
              native-image \
                --no-fallback \
                --static \
                --libc=musl \
                --enable-url-protocols=http,https \
                -H:Name=spring-cloud-native \
                -H:Class=com.example.person.FunctionConfiguration \
                -H:+ReportExceptionStackTraces \
                -H:+PrintAnalysisCallTree \
                --verbose \
                --initialize-at-build-time \
                --native-image-info \
                --target=arm64-linux

      - name: Create bootstrap file and package ZIP
        run: |
          echo '#!/bin/sh' > bootstrap
          echo './spring-cloud-native' >> bootstrap
          chmod +x bootstrap
          mv bootstrap target/
          cd target
          zip function.zip spring-cloud-native bootstrap

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-artifacts
          path: |
            target/function.zip
            target/bootstrap
            target/spring-cloud-native
            template.yaml

  deploy:
    name: Deploy Lambda and API Gateway
    runs-on: ubuntu-latest
    needs: build
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lambda-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Ensure S3 bucket exists
        run: |
          aws s3api head-bucket --bucket ${{ secrets.S3_DEPLOY_BUCKET }} 2>/dev/null || \
          aws s3api create-bucket --bucket ${{ secrets.S3_DEPLOY_BUCKET }} --region ${{ env.AWS_REGION }}

      - name: Package SAM template
        run: |
          sam package \
            --template-file template.yaml \
            --output-template-file packaged.yaml \
            --s3-bucket ${{ secrets.S3_DEPLOY_BUCKET }}

      - name: Deploy SAM template
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name person-crud-stack \
            --capabilities CAPABILITY_IAM