name: Build and Deploy to AWS Lambda with SAM

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    name: Build native image and prepare artifacts
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        run: mvn clean package native:compile

      - name: Create bootstrap file
        run: |
          echo '#!/bin/sh' > bootstrap
          echo './spring-cloud-native' >> bootstrap
          chmod +x bootstrap
          mv bootstrap target/

      - name: Package Lambda ZIP
        run: |
          cd target
          zip function.zip spring-cloud-native bootstrap

      - name: Upload build artifacts for later steps
        uses: actions/upload-artifact@v4
        with:
          name: lambda-artifacts
          path: |
            target/
            template.yaml

  deploy-sam:
    runs-on: ubuntu-latest
    name: Deploy Lambda and API Gateway
    needs: build-lambda
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lambda-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Ensure S3 bucket exists
        run: |
          aws s3api head-bucket --bucket ${{ secrets.S3_DEPLOY_BUCKET }} 2>/dev/null || \
          aws s3api create-bucket \
            --bucket ${{ secrets.S3_DEPLOY_BUCKET }} \
            --region ${{ env.AWS_REGION }}

      - name: Package SAM template
        run: |
          sam package \
            --template-file template.yaml \
            --output-template-file packaged.yaml \
            --s3-bucket ${{ secrets.S3_DEPLOY_BUCKET }} \
            --region ${{ env.AWS_REGION }}

      - name: Deploy SAM template
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name person-crud-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }}