name: Build and Deploy Native Lambda with SAM

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build native image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Native Image and tools
        run: |
          gu install native-image
          sudo apt-get update && sudo apt-get install -y musl-tools zlib1g-dev

      - name: Build native image with Maven
        run: mvn clean package -Pnative

      - name: Verify binary is ARM64
        run: file target/spring-cloud-native

      - name: Create bootstrap file and zip
        run: |
          echo '#!/bin/sh' > target/bootstrap
          echo './spring-cloud-native' >> target/bootstrap
          chmod +x target/bootstrap
          cd target
          zip function.zip spring-cloud-native bootstrap

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-artifacts
          path: |
            target/function.zip
            template.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lambda-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Ensure S3 bucket exists
        run: |
          aws s3api head-bucket --bucket ${{ secrets.S3_DEPLOY_BUCKET }} 2>/dev/null || \
          aws s3api create-bucket \
            --bucket ${{ secrets.S3_DEPLOY_BUCKET }} \
            --region ${{ env.AWS_REGION }}

      - name: Package SAM template
        run: |
          sam package \
            --template-file template.yaml \
            --output-template-file packaged.yaml \
            --s3-bucket ${{ secrets.S3_DEPLOY_BUCKET }}

      - name: Deploy with SAM
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name person-crud-stack \
            --capabilities CAPABILITY_IAM