name: Build and Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build native image
      run: mvn clean package native:compile
    - name: Package Lambda ZIP
      run: |
        cd target
        zip -r function.zip spring-cloud-native
    - name: Create Lambda function (if not exists)
      run: |
        aws lambda get-function --function-name person-crud-prod || \
        aws lambda create-function \
          --function-name person-crud-prod \
          --runtime provided.al2 \
          --handler not.used.in.native.image \
          --role arn:aws:iam::905418179757:role/lambda-basic-execution-role \
          --zip-file fileb://target/function.zip \
          --architectures arm64 \
          --memory-size 512 \
          --timeout 30
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
    - name: Deploy to AWS Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        function_name: person-crud-prod
        zip_file: ./target/function.zip
