name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Build native image
      run: ./mvnw -Pnative clean package

    - name: Deploy to AWS Lambda
      run: echo "Simulate AWS Lambda deployment here"
