name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '21'
          distribution: 'graalvm-community'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build native image
        run: mvn -Pnative native:compile

      - name: Deploy to AWS Lambda
        run: echo "Simulate AWS Lambda deployment here"
